//// <auto-generated />
//using System;
//using Kyrsach;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace Kyrsach.Migrations
//{
//    [DbContext(typeof(SerovaContext))]
//    [Migration("20240228212705_addGroup")]
//    partial class addGroup
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "6.0.16")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

//            modelBuilder.Entity("Kyrsach.Models.Answer", b =>
//                {
//                    b.Property<int>("IdAnswer")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnswer"), 1L, 1);

//                    b.Property<string>("Answer1")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)")
//                        .HasColumnName("Answer");

//                    b.Property<int>("IdAnswersUser")
//                        .HasColumnType("int");

//                    b.Property<int>("IdQuestion")
//                        .HasColumnType("int");

//                    b.Property<string>("Loyal")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)")
//                        .HasColumnName("loyal");

//                    b.HasKey("IdAnswer");

//                    b.HasIndex(new[] { "IdAnswersUser" }, "IX_Answer_IdAnswersUser");

//                    b.HasIndex(new[] { "IdQuestion" }, "IX_Answer_IdQuestion");

//                    b.ToTable("Answer", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.AnswersUser", b =>
//                {
//                    b.Property<int>("IdAnswersUser")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnswersUser"), 1L, 1);

//                    b.Property<int>("CountCurrent")
//                        .HasColumnType("int");

//                    b.Property<string>("IdUser")
//                        .IsRequired()
//                        .HasMaxLength(450)
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<DateTime?>("Time")
//                        .HasColumnType("datetime");

//                    b.Property<string>("UserModelId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("IdAnswersUser");

//                    b.HasIndex("UserModelId");

//                    b.ToTable("AnswersUser", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Category", b =>
//                {
//                    b.Property<int>("IdCategory")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"), 1L, 1);

//                    b.Property<string>("NameCategory")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<byte[]>("Picture")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("Type")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)")
//                        .HasColumnName("type");

//                    b.Property<int?>("WhoAnsweredCategory")
//                        .HasColumnType("int");

//                    b.HasKey("IdCategory")
//                        .HasName("PK_Сategory");

//                    b.ToTable("Category", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Group", b =>
//                {
//                    b.Property<int>("IdGroup")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroup"), 1L, 1);

//                    b.Property<string>("NameGroup")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.HasKey("IdGroup");

//                    b.ToTable("Group", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Pair", b =>
//                {
//                    b.Property<int>("IdPair")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPair"), 1L, 1);

//                    b.Property<byte[]>("Card1Img")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("Card1Text")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<byte[]>("Card2Img")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("Card2Text")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<int>("IdCategory")
//                        .HasColumnType("int");

//                    b.HasKey("IdPair");

//                    b.HasIndex(new[] { "IdCategory" }, "IX_Pair_IdCategory");

//                    b.ToTable("Pair", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Question", b =>
//                {
//                    b.Property<int>("IdQuestion")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuestion"), 1L, 1);

//                    b.Property<string>("CorrectAnswer")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<int>("IdTest")
//                        .HasColumnType("int");

//                    b.Property<string>("Option1")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Option2")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Option3")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Option4")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Option5")
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<byte[]>("PictureTest")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("TextQuetion")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("WhoAnsweredQuestion")
//                        .HasColumnType("int");

//                    b.HasKey("IdQuestion");

//                    b.HasIndex(new[] { "IdTest" }, "IX_Question_IdTest");

//                    b.ToTable("Question", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Quez", b =>
//                {
//                    b.Property<int>("IdQuez")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdQuez"), 1L, 1);

//                    b.Property<int>("IdTest")
//                        .HasColumnType("int");

//                    b.Property<byte[]>("Pic1")
//                        .HasColumnType("varbinary(max)")
//                        .HasColumnName("pic1");

//                    b.Property<byte[]>("Pic2")
//                        .HasColumnType("varbinary(max)")
//                        .HasColumnName("pic2");

//                    b.Property<byte[]>("Pic3")
//                        .HasColumnType("varbinary(max)")
//                        .HasColumnName("pic3");

//                    b.Property<byte[]>("Pic4")
//                        .HasColumnType("varbinary(max)")
//                        .HasColumnName("pic4");

//                    b.Property<byte[]>("Pic5")
//                        .HasColumnType("varbinary(max)")
//                        .HasColumnName("pic5");

//                    b.Property<string>("Q1")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Q2")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Q3")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Q4")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("Q5")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.HasKey("IdQuez");

//                    b.HasIndex(new[] { "IdTest" }, "IX_Quez_IdTest");

//                    b.ToTable("Quez", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Test", b =>
//                {
//                    b.Property<int>("IdTest")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTest"), 1L, 1);

//                    b.Property<int>("IdCategory")
//                        .HasColumnType("int");

//                    b.Property<string>("NameTest")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<int?>("WhoAnsweredTest")
//                        .HasColumnType("int");

//                    b.HasKey("IdTest");

//                    b.HasIndex(new[] { "IdCategory" }, "IX_Test_IdCategory");

//                    b.ToTable("Test", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.UserModel", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("IdGroup")
//                        .HasColumnType("int");

//                    b.Property<int?>("IdGroupNavigationIdGroup")
//                        .HasColumnType("int");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("IdGroupNavigationIdGroup");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("AspNetUsers", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
//                {
//                    b.Property<string>("Id")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("RoleId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("UserId")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("RoleId")
//                        .HasColumnType("nvarchar(450)");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.Property<string>("UserId")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("Kyrsach.Models.Answer", b =>
//                {
//                    b.HasOne("Kyrsach.Models.AnswersUser", "IdAnswersUserNavigation")
//                        .WithMany("Answers")
//                        .HasForeignKey("IdAnswersUser")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired()
//                        .HasConstraintName("FK_Answer_AnswersUser");

//                    b.HasOne("Kyrsach.Models.Question", "IdQuestionNavigation")
//                        .WithMany("Answers")
//                        .HasForeignKey("IdQuestion")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired()
//                        .HasConstraintName("FK_Answer_Question");

//                    b.Navigation("IdAnswersUserNavigation");

//                    b.Navigation("IdQuestionNavigation");
//                });

//            modelBuilder.Entity("Kyrsach.Models.AnswersUser", b =>
//                {
//                    b.HasOne("Kyrsach.Models.UserModel", null)
//                        .WithMany("AnswersUsers")
//                        .HasForeignKey("UserModelId");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Pair", b =>
//                {
//                    b.HasOne("Kyrsach.Models.Category", "IdCategoryNavigation")
//                        .WithMany("Pairs")
//                        .HasForeignKey("IdCategory")
//                        .IsRequired()
//                        .HasConstraintName("FK_Pair_Category");

//                    b.Navigation("IdCategoryNavigation");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Question", b =>
//                {
//                    b.HasOne("Kyrsach.Models.Test", "IdTestNavigation")
//                        .WithMany("Questions")
//                        .HasForeignKey("IdTest")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired()
//                        .HasConstraintName("FK_Question_Test");

//                    b.Navigation("IdTestNavigation");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Quez", b =>
//                {
//                    b.HasOne("Kyrsach.Models.Test", "IdTestNavigation")
//                        .WithMany("Quezs")
//                        .HasForeignKey("IdTest")
//                        .IsRequired()
//                        .HasConstraintName("FK_Quez_Test");

//                    b.Navigation("IdTestNavigation");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Test", b =>
//                {
//                    b.HasOne("Kyrsach.Models.Category", "IdCategoryNavigation")
//                        .WithMany("Tests")
//                        .HasForeignKey("IdCategory")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired()
//                        .HasConstraintName("FK_Test_Сategory");

//                    b.Navigation("IdCategoryNavigation");
//                });

//            modelBuilder.Entity("Kyrsach.Models.UserModel", b =>
//                {
//                    b.HasOne("Kyrsach.Models.Group", "IdGroupNavigation")
//                        .WithMany("Users")
//                        .HasForeignKey("IdGroupNavigationIdGroup");

//                    b.Navigation("IdGroupNavigation");
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
//                {
//                    b.HasOne("Kyrsach.Models.UserModel", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
//                {
//                    b.HasOne("Kyrsach.Models.UserModel", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
//                {
//                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Kyrsach.Models.UserModel", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
//                {
//                    b.HasOne("Kyrsach.Models.UserModel", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Kyrsach.Models.AnswersUser", b =>
//                {
//                    b.Navigation("Answers");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Category", b =>
//                {
//                    b.Navigation("Pairs");

//                    b.Navigation("Tests");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Group", b =>
//                {
//                    b.Navigation("Users");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Question", b =>
//                {
//                    b.Navigation("Answers");
//                });

//            modelBuilder.Entity("Kyrsach.Models.Test", b =>
//                {
//                    b.Navigation("Questions");

//                    b.Navigation("Quezs");
//                });

//            modelBuilder.Entity("Kyrsach.Models.UserModel", b =>
//                {
//                    b.Navigation("AnswersUsers");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
